version: '3'

services:

  browserless:
    image: browserless/chrome
    ports:
      - "3000:3000"

  node:
    image: node:18-bullseye
    volumes:
      - ./:/var/www
    depends_on:
      - browserless